@extends('layouts.app')

@section('title', 'Identidad del portal')

@section('content')
<div class="page-heading identity-heading"><div><span class="eyebrow">Administración · CCyF</span><h1>Identidad del portal</h1><p>Administra la marca, el PDF y la tarjeta de convocatoria que aparecerán en Inicio.</p></div></div>
@if($errors->any())<div class="form-errors" role="alert">Revisa los campos marcados para guardar los cambios.</div>@endif
<div class="brand-editor">
    <section class="panel" aria-labelledby="brand-form-title">
        <h2 id="brand-form-title">Imagen y mensaje</h2>
        <p class="muted">El logo aparece encima del formulario de acceso y en el encabezado del sistema.</p>
        <form method="post" action="{{ route('branding.update') }}" enctype="multipart/form-data" data-branding-form data-current-logo="{{ $logoUrl }}" data-default-logo="{{ asset('images/ccyf-default.svg') }}">
            @csrf @method('PUT')
            <div><label for="brand-title">Título del portal</label><input id="brand-title" name="title" type="text" maxlength="120" value="{{ old('title', $branding->title) }}" required><small class="field-help">Se muestra junto al logo. Usa un nombre breve y reconocible.</small>@error('title')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
            <div><label for="brand-motto">Lema principal</label><input id="brand-motto" name="motto" type="text" maxlength="160" value="{{ old('motto', $branding->motto) }}" required><small class="field-help">Aparece de forma destacada en la pantalla de acceso.</small>@error('motto')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
            <div><label for="brand-logo">Logo o imagen institucional</label><div class="brand-upload-note"><img id="brand-upload-preview" src="{{ $logoUrl }}" alt="Vista previa del logo"><div><strong>Vista previa de la imagen</strong><small>PNG, JPG o WebP · máximo 4 MB · entre 80 × 80 y 4000 × 4000 píxeles.</small></div></div><input id="brand-logo" name="logo" type="file" accept="image/png,image/jpeg,image/webp" aria-describedby="brand-logo-help brand-logo-status"><small class="field-help" id="brand-logo-help">Al elegir una imagen, la verás aquí y en la tarjeta de acceso. El cambio se aplica al guardar.</small><div class="brand-file-status" id="brand-logo-status" role="status" aria-live="polite" data-state="neutral"><strong>Imagen actual</strong><small>Selecciona un archivo para comprobarlo antes de guardar.</small></div>@error('logo')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
            @if($branding->logo_path)<label class="brand-remove" for="brand-remove"><input id="brand-remove" type="checkbox" name="remove_logo" value="1" @checked(old('remove_logo'))>Quitar el logo cargado y usar la marca predeterminada de CCyF</label>@endif
            <div class="brand-form-actions"><button class="button" type="submit" data-branding-submit>Guardar identidad</button></div>
        </form>
    </section>
    <aside class="panel brand-preview" aria-label="Vista previa del acceso">
        <div class="brand-preview-header"><img id="brand-preview-logo" src="{{ $logoUrl }}" alt=""><div><strong>CCyF</strong><small>COBAEM · Estado de México</small></div></div>
        <div class="brand-preview-body"><span>Vista previa</span><h2 id="brand-preview-motto">{{ old('motto', $branding->motto) }}</h2><p id="brand-preview-title">{{ old('title', $branding->title) }}</p></div>
    </aside>
</div>
<section class="panel brand-document-panel" aria-labelledby="brand-document-title">
    <div class="brand-document-intro"><div><span class="eyebrow">Inicio · Concursantes y administradores</span><h2 id="brand-document-title">Documento destacado</h2><p>Publica un PDF para consultarlo desde Inicio. Se abrirá en un visor de varias páginas, también en tabletas.</p></div><span class="pill {{ $documentAvailable ? 'pill-ready' : 'pill-neutral' }}">{{ $documentAvailable ? 'Publicado' : 'Sin documento' }}</span></div>
    <form method="post" action="{{ route('branding.document.update') }}" enctype="multipart/form-data" data-portal-document-form data-current-document="{{ $documentAvailable ? route('branding.document') : '' }}">
        @csrf @method('PUT')
        <div class="brand-document-fields">
            <div><label for="document-title">Título de la tarjeta</label><input id="document-title" name="document_title" type="text" maxlength="120" value="{{ old('document_title', $branding->document_title) }}" required><small class="field-help">Ejemplo: Guía para participar en la convocatoria.</small>@error('document_title')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
            <div><label for="document-description">Descripción breve</label><input id="document-description" name="document_description" type="text" maxlength="240" value="{{ old('document_description', $branding->document_description) }}"><small class="field-help">Aparecerá debajo del título en Inicio.</small>@error('document_description')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
        </div>
        <div class="brand-document-upload"><div><label for="document-file">Archivo PDF</label><input id="document-file" name="document" type="file" accept="application/pdf,.pdf" aria-describedby="document-file-status"><small class="field-help">Máximo 15 MB. Al reemplazarlo, el PDF anterior se elimina después de guardar.</small>@error('document')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div><div class="brand-file-status" id="document-file-status" role="status" aria-live="polite" data-state="neutral"><strong>{{ $documentAvailable ? 'PDF publicado' : 'Aún no hay PDF publicado' }}</strong><small>{{ $documentAvailable ? 'Puedes consultarlo o elegir uno nuevo.' : 'Selecciona un archivo para mostrarlo a los permisionarios.' }}</small></div></div>
        <div class="brand-document-actions">@if($documentAvailable)<label class="brand-remove" for="remove-document"><input id="remove-document" type="checkbox" name="remove_document" value="1" @checked(old('remove_document'))>Retirar PDF del inicio</label>@endif<div><a id="document-preview-link" class="outline-button button-link" href="{{ $documentAvailable ? route('branding.document') : '#' }}" data-review-document data-document-name="{{ $branding->document_title }}" data-document-mime="application/pdf" @if(! $documentAvailable) hidden @endif>Vista previa PDF ↗</a><button class="button" type="submit" data-document-submit>Guardar documento</button></div></div>
    </form>
</section>
<section class="panel brand-announcement-panel" aria-labelledby="brand-announcement-title">
    <div class="brand-document-intro"><div><span class="eyebrow">Inicio · Concursantes y administradores</span><h2 id="brand-announcement-title">Tarjeta de convocatoria</h2><p>Publica una imagen, un video o ambos. Si agregas ambos, la imagen aparecerá como portada del video. Puedes incluir hasta dos enlaces.</p></div><span class="pill {{ $branding->announcement_visible ? 'pill-ready' : 'pill-neutral' }}">{{ $branding->announcement_visible ? 'Visible' : 'Oculta' }}</span></div>
    <form method="post" action="{{ route('branding.announcement.update') }}" enctype="multipart/form-data" data-announcement-form data-current-image="{{ $announcementImageAvailable ? route('branding.announcement.media', ['kind' => 'imagen']) : '' }}" data-current-video="{{ $announcementVideoAvailable ? route('branding.announcement.media', ['kind' => 'video']) : '' }}" data-current-video-type="{{ str_ends_with((string) $branding->announcement_video_path, '.webm') ? 'video/webm' : 'video/mp4' }}">
        @csrf @method('PUT')
        <input type="hidden" name="announcement_visible" value="0">
        <label class="announcement-visibility" for="announcement-visible"><input id="announcement-visible" name="announcement_visible" type="checkbox" value="1" @checked(old('announcement_visible', $branding->announcement_visible))><span><strong>Mostrar tarjeta en Inicio</strong><small>Si la ocultas, la configuración y los archivos se conservan para publicarla después.</small></span></label>
        <div class="brand-announcement-layout">
            <div class="brand-announcement-fields">
                <div><label for="announcement-title">Título de la tarjeta</label><input id="announcement-title" name="announcement_title" maxlength="120" value="{{ old('announcement_title', $branding->announcement_title) }}" required>@error('announcement_title')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
                <div><label for="announcement-description">Texto breve</label><textarea id="announcement-description" name="announcement_description" maxlength="240" rows="3" placeholder="Consulta las bases y fechas de participación.">{{ old('announcement_description', $branding->announcement_description) }}</textarea><small class="field-help">Máximo 240 caracteres.</small>@error('announcement_description')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
                <div class="announcement-upload-grid">
                    <div><label for="announcement-image">Imagen o portada</label><input id="announcement-image" name="announcement_image" type="file" accept="image/png,image/jpeg,image/webp"><small class="field-help">PNG, JPG o WebP · máximo 6 MB · desde 300 × 200 px.</small>@if($announcementImageAvailable)<label class="brand-remove" for="remove-announcement-image"><input id="remove-announcement-image" name="remove_announcement_image" type="checkbox" value="1">Quitar imagen actual</label>@endif @error('announcement_image')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
                    <div><label for="announcement-video">Video opcional</label><input id="announcement-video" name="announcement_video" type="file" accept="video/mp4,video/webm,.mp4,.webm"><small class="field-help">MP4 o WebM · máximo 50 MB · reproducción manual.</small>@if($announcementVideoAvailable)<label class="brand-remove" for="remove-announcement-video"><input id="remove-announcement-video" name="remove_announcement_video" type="checkbox" value="1">Quitar video actual</label>@endif @error('announcement_video')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
                </div>
                @foreach([1, 2] as $number)
                    <fieldset class="announcement-link-fieldset"><legend>Enlace {{ $number }}</legend><div class="announcement-link-grid"><div><label for="announcement-link-{{ $number }}-label">Texto del botón</label><input id="announcement-link-{{ $number }}-label" name="announcement_link_{{ $number }}_label" maxlength="80" value="{{ old('announcement_link_'.$number.'_label', $branding->{'announcement_link_'.$number.'_label'}) }}" placeholder="{{ $number === 1 ? 'Consultar convocatoria' : 'Más información' }}">@error('announcement_link_'.$number.'_label')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div><div><label for="announcement-link-{{ $number }}-url">URL completa</label><input id="announcement-link-{{ $number }}-url" name="announcement_link_{{ $number }}_url" type="url" maxlength="2048" value="{{ old('announcement_link_'.$number.'_url', $branding->{'announcement_link_'.$number.'_url'}) }}" placeholder="https://..."></div></div>@error('announcement_link_'.$number.'_url')<span class="field-error" role="alert">{{ $message }}</span>@enderror<input type="hidden" name="announcement_link_{{ $number }}_blank" value="0"><label class="brand-remove" for="announcement-link-{{ $number }}-blank"><input id="announcement-link-{{ $number }}-blank" name="announcement_link_{{ $number }}_blank" type="checkbox" value="1" @checked(old('announcement_link_'.$number.'_blank', $branding->{'announcement_link_'.$number.'_blank'}))>Abrir este enlace en otra pestaña</label></fieldset>
                @endforeach
            </div>
            <aside class="announcement-preview-wrap" aria-label="Vista previa de la tarjeta"><span class="eyebrow">Vista previa · Sin guardar</span><article class="portal-announcement-card"><div class="portal-announcement-media" id="announcement-media-preview">@if($announcementVideoAvailable)<video controls playsinline preload="none" @if($announcementImageAvailable) poster="{{ route('branding.announcement.media', ['kind' => 'imagen']) }}" @endif><source src="{{ route('branding.announcement.media', ['kind' => 'video']) }}" type="{{ str_ends_with($branding->announcement_video_path, '.webm') ? 'video/webm' : 'video/mp4' }}"></video>@elseif($announcementImageAvailable)<img src="{{ route('branding.announcement.media', ['kind' => 'imagen']) }}" alt="Vista previa de la convocatoria">@else<div class="portal-announcement-placeholder" aria-hidden="true"><span>CCyF</span><strong>Convocatorias</strong></div>@endif</div><div class="portal-announcement-body"><span class="eyebrow">Convocatoria · COBAEM</span><h3 id="announcement-title-preview">{{ old('announcement_title', $branding->announcement_title) }}</h3><p id="announcement-description-preview">{{ old('announcement_description', $branding->announcement_description) }}</p><div class="portal-announcement-actions" id="announcement-links-preview">@foreach([1, 2] as $number)@if($branding->{'announcement_link_'.$number.'_url'})<span>{{ $branding->{'announcement_link_'.$number.'_label'} ?: ($number === 1 ? 'Consultar convocatoria' : 'Más información') }} <span aria-hidden="true">→</span></span>@endif @endforeach</div></div></article><p class="announcement-preview-note" id="announcement-preview-status" role="status">{{ $branding->announcement_visible ? 'La tarjeta está visible en Inicio.' : 'La tarjeta está oculta en Inicio.' }}</p></aside>
        </div>
        <div class="brand-document-actions"><span class="field-help">Los cambios se verán en Inicio después de guardar.</span><button class="button" type="submit" data-announcement-submit>Guardar tarjeta</button></div>
    </form>
</section>
@include('revision.document-viewer', ['viewerEyebrow' => 'Documento para participantes'])
<script src="{{ asset('js/branding-preview.js') }}?v=20261002-1" defer></script>
<script src="{{ asset('js/announcement-preview.js') }}?v=20261003-1" defer></script>
@endsection
