@extends('layouts.app')

@section('title', 'Expediente histórico '.$registration->doc_id)
@section('content')
<a class="back-link" href="{{ route('revision.finished') }}">← Convocatorias finalizadas</a>
<div class="page-heading review-heading"><div><span class="eyebrow">Expediente histórico · HIST-{{ str_pad((string) $registration->doc_id, 5, '0', STR_PAD_LEFT) }}</span><h1>{{ $registration->solicitante ?: 'Participante' }}</h1><p>{{ $registration->convocatoria_nombre ?: 'Convocatoria histórica' }} · {{ $registration->servicio_nombre }} · {{ $registration->doc_exter ?: $registration->plantel_real }}</p></div><span class="pill pill-neutral">Histórico</span></div>
<div class="info-strip">Este expediente conserva el resultado registrado en el sistema anterior.</div>
<div class="review-detail-grid"><section class="panel"><span class="eyebrow">Datos de participación</span><h2>Propuesta</h2><dl class="review-facts"><div><dt>Folio histórico</dt><dd>HIST-{{ str_pad((string) $registration->doc_id, 5, '0', STR_PAD_LEFT) }}</dd></div><div><dt>Plantel</dt><dd>{{ $registration->doc_exter ?: $registration->plantel_real }}</dd></div><div><dt>Servicio</dt><dd>{{ $registration->servicio_nombre }}</dd></div><div><dt>Recibido</dt><dd>{{ $registration->fech_crea ? \Illuminate\Support\Carbon::parse($registration->fech_crea)->format('d/m/Y H:i') : 'Sin fecha registrada' }}</dd></div><div><dt>Comentarios</dt><dd>{{ $registration->doc_descrip ?: 'Sin comentarios' }}</dd></div></dl></section>
    <section class="panel review-result"><span class="eyebrow">Resultado registrado</span><h2>{{ (int) $registration->doc_designado === 1 ? 'Designado' : (str_contains(mb_strtolower((string) $registration->doc_respuesta), 'no aceptad') ? 'No aceptado' : 'No designado') }}</h2><p>{{ $registration->doc_respuesta ?: 'No se registró una respuesta escrita.' }}</p>@if ((int) $registration->doc_designado === 1)<div class="review-result-facts"><span>{{ $registration->doc_fech_ini ?: 'Sin fecha de inicio' }} al {{ $registration->doc_fech_fin ?: 'sin fecha de fin' }}</span>@if ($registration->monto)<strong>Monto inicial: ${{ number_format((float) $registration->monto, 2) }}</strong>@endif</div>@endif<small>Finalizado {{ $registration->fech_concluido ? \Illuminate\Support\Carbon::parse($registration->fech_concluido)->format('d/m/Y H:i') : 'sin fecha registrada' }}</small></section></div>
<section class="panel"><div class="section-bar"><div><span class="eyebrow">Resolución y evaluación</span><h2>Documentos finales</h2></div></div>
    <div class="review-final-documents">
        <div class="review-final-document"><strong>{{ (int) $registration->doc_designado === 1 ? 'Carta de designación' : 'Carta de no designación' }}</strong><p>{{ $resultadoPdfDisponible ? 'PDF original archivado para este expediente.' : 'La carta de este expediente no se encontró en los archivos de esta copia.' }}</p>@if ($resultadoPdfDisponible)<a class="button button-link" href="{{ route('revision.historical-result-pdf', $registration->doc_id) }}" target="_blank" rel="noopener">Ver carta PDF ↗</a>@else<span class="muted">Carta PDF no disponible</span>@endif</div>
        <div class="review-final-document"><strong>Evaluación final</strong><p>El sistema anterior generaba este reporte al consultarlo. {{ $evaluacionRegistrada ? 'Hay datos de evaluación, pero no se conserva el PDF generado en esta copia.' : 'No hay una evaluación final registrada para este expediente en la base de datos de esta copia.' }}</p><span class="muted">PDF no disponible</span></div>
    </div>
</section>
<section class="panel"><div class="section-bar"><div><span class="eyebrow">Documentación vigente</span><h2>Archivos del expediente</h2></div><span class="pill pill-neutral">{{ $requirements->count() }} archivos</span></div>
    @if ($previewDocuments->isEmpty())<p class="muted">No hay archivos asociados a este registro.</p>@else<div class="review-file-grid">@foreach ($previewDocuments as $document)<a class="review-file" href="{{ $document['url'] }}" data-review-document data-document-name="{{ $document['label'] }}" data-document-mime="{{ $document['mime'] }}"><span aria-hidden="true">{{ $document['mime'] === 'application/pdf' ? 'PDF' : 'DOC' }}</span><strong>{{ $document['label'] }}</strong><small>Ver en modal ↗</small></a>@endforeach</div>@endif
</section>
@include('revision.document-viewer')
@endsection
