@extends('layouts.app')

@section('title', 'Expediente '.$registration->folio)
@section('content')
<a class="back-link" href="{{ $registration->estado === 'Finalizado' ? route('revision.finished') : route('revision.pending') }}">← {{ $registration->estado === 'Finalizado' ? 'Convocatorias finalizadas' : 'Convocatorias pendientes' }}</a>
<div class="page-heading review-heading"><div><span class="eyebrow">Expediente actual · {{ $registration->folio }}</span><h1>{{ $registration->solicitante }}</h1><p>{{ $registration->convocatoria_nombre }} · {{ $registration->servicio_nombre }} · {{ $registration->plantel_nombre }}</p></div><span class="pill {{ $registration->estado === 'Finalizado' ? 'pill-ready' : 'pill-pending' }}">{{ $registration->estado }}</span></div>
<div class="review-detail-grid">
    <section class="panel"><span class="eyebrow">01 · Datos del registro</span><h2>Propuesta recibida</h2><dl class="review-facts"><div><dt>Folio</dt><dd>{{ $registration->folio }}</dd></div><div><dt>Plantel</dt><dd>{{ $registration->plantel_nombre }}</dd></div><div><dt>Servicio</dt><dd>{{ $registration->servicio_nombre }}</dd></div><div><dt>Enviado</dt><dd>{{ \Illuminate\Support\Carbon::parse($registration->enviado_at)->format('d/m/Y H:i') }}</dd></div><div><dt>Dirigido a</dt><dd>{{ $registration->dirigido_a }}</dd></div><div><dt>Comentarios</dt><dd>{{ $registration->comentarios }}</dd></div></dl></section>
    <section class="panel"><span class="eyebrow">02 · Oferta económica</span><h2>Precios propuestos</h2><div class="review-price-list">@foreach ($prices as $price)<div><span>{{ $price->producto_nombre }} <small>{{ $price->unidad }}</small></span><strong>${{ number_format((float) $price->precio, 2) }}</strong></div>@endforeach</div></section>
</div>
<section class="panel"><div class="section-bar"><div><span class="eyebrow">03 · Documentación</span><h2>Expediente digital</h2></div><span class="pill pill-neutral">{{ $files->count() }} archivos PDF</span></div><div class="review-file-grid">@foreach ($files as $file)<a class="review-file" href="{{ route('revision.file', [$registration->id, $file->id]) }}"><span aria-hidden="true">PDF</span><strong>{{ $file->nombre }}</strong><small>{{ number_format($file->bytes / 1024) }} KB · Descargar PDF ↓</small></a>@endforeach</div></section>
@if ($registration->estado === 'Finalizado')
    <section class="panel review-result"><span class="eyebrow">04 · Resultado</span><h2>{{ match ($registration->decision) { 'designado' => 'Designado', 'no_aceptado' => 'No aceptado', default => 'No designado' } }}</h2><p>{{ $registration->respuesta }}</p>@if ($registration->decision === 'designado')<div class="review-result-facts"><span>Del {{ $registration->fecha_inicio }} al {{ $registration->fecha_fin }}</span><strong>Monto inicial: ${{ number_format((float) $registration->monto, 2) }}</strong></div>@endif</section>
@elseif (app(\App\Services\LegacyMenu::class)->allows(auth()->user(), 'gestionOficio'))
    <section class="panel review-decision"><span class="eyebrow">04 · Resolución</span><h2>Finalizar propuesta</h2><p class="muted">La decisión y la respuesta quedarán guardadas en el expediente.</p>
        @if ($errors->any())<div class="form-errors" role="alert"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="post" action="{{ route('revision.finish', $registration->id) }}">@csrf
            <div class="review-decision-fields"><label>Decisión<select name="decision" id="decision" required><option value="">Selecciona el resultado</option><option value="designado" @selected(old('decision') === 'designado')>Designar al plantel</option><option value="no_designado" @selected(old('decision') === 'no_designado')>No designar</option><option value="no_aceptado" @selected(old('decision') === 'no_aceptado')>No aceptar propuesta</option></select></label><label>Respuesta para el expediente<textarea name="respuesta" rows="3" maxlength="250" required placeholder="Explica el resultado en un máximo de 250 caracteres">{{ old('respuesta') }}</textarea></label></div>
            <div class="review-designation" id="designation-fields" hidden><label>Fecha de inicio<input type="date" name="fecha_inicio" value="{{ old('fecha_inicio') }}"></label><label>Fecha de fin<input type="date" name="fecha_fin" value="{{ old('fecha_fin') }}"></label><label>Monto inicial ($)<input type="number" name="monto" min="0.01" step="0.01" value="{{ old('monto') }}"></label></div>
            <div class="form-footer"><p>Comprueba los PDF y precios antes de finalizar. Este resultado ya no aparecerá en Pendientes.</p><button class="button" type="submit" onclick="return confirm('¿Finalizar esta propuesta con el resultado indicado?')">Guardar resultado</button></div>
        </form>
    </section>
    <script>const decision = document.getElementById('decision'); const designation = document.getElementById('designation-fields'); const updateDesignation = () => { const enabled = decision.value === 'designado'; designation.hidden = !enabled; designation.querySelectorAll('input').forEach(input => { input.required = enabled; }); }; decision.addEventListener('change', updateDesignation); updateDesignation();</script>
@endif
@endsection
