@extends('layouts.app')
@push('head')<link rel="stylesheet" href="{{ asset('css/contratos.css') }}?v=20261002-1">@endpush
@section('title', 'Plantilla de contrato')
@section('content')
<a class="back-link" href="{{ route('contratos.index', ['servicio'=>$service]) }}">← Volver a contratos</a>
<div class="page-heading contract-heading"><div><span class="eyebrow">CCyF · Plantilla jurídica</span><h1>Contrato de {{ $service === 'cafeteria' ? 'cafetería' : 'fotocopiado' }}</h1><p>Edita el texto y conserva cada versión. Los campos entre llaves se llenan con los datos del expediente.</p></div><span class="contract-mini-badge">{{ $current ? ($current->source === 'local' ? 'Versión local' : 'Plantilla original') : 'Sin plantilla' }}</span></div>
@if($errors->any())<div class="form-errors" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="contract-editor-layout"><form id="contract-template-form" class="panel contract-editor-card" method="post" action="{{ route('contratos.template.save', $service) }}">@csrf<div class="contract-editor-head"><div><span class="eyebrow">Texto del documento</span><h2>Editar plantilla</h2></div><span>{{ $current ? 'Último cambio: '.$current->updated_at : 'Nueva plantilla' }}</span></div>
    @if($viewingVersion)<div class="contract-version-banner">Estás consultando la versión #{{ $viewingVersion->id }}. Si guardas, se creará una nueva versión sin borrar las anteriores. <a href="{{ route('contratos.template', $service) }}">Volver a la versión vigente</a></div>@endif
    <p class="contract-help">Guarda una nueva versión cuando termines. Revisa después el PDF de un expediente antes de enviarlo.</p>
    <div class="contract-type-controls"><div><label for="contract-font-family">Letra del PDF</label><select id="contract-font-family" name="font_family" required>@foreach($fontFamilies as $value => $label)<option value="{{ $value }}" @selected(old('font_family', $editor?->font_family ?? 'dejavusans') === $value)>{{ $label }}</option>@endforeach<option disabled>Gotham Book · pendiente de archivo .ttf</option></select></div><div><label for="contract-font-size">Tamaño (puntos)</label><input id="contract-font-size" name="font_size" type="number" min="7" max="14" step="0.5" required value="{{ old('font_size', $editor?->font_size ?? 9) }}"></div></div>
    <p class="contract-help">El tamaño inicial es 9 puntos. Gotham Book está instalada como OTF con contornos CFF; para usarla en el PDF se necesita una versión TrueType compatible (.ttf).</p>
    <label id="contract-body-label" for="contract-body">Contenido del contrato</label>
    <textarea id="contract-body" name="body" class="contract-tinymce" rows="24" data-tiny-base="{{ asset('vendor/tinymce') }}" data-upload-url="{{ route('contratos.images.upload') }}" aria-labelledby="contract-body-label">{{ old('body', $editorHtml) }}</textarea>
    <p class="contract-help">Da formato al texto seleccionado e inserta tablas o imágenes PNG/JPG de hasta 2 MB. El PDF conservará el formato compatible con la plantilla.</p>
    <div class="contract-signer-head"><span class="eyebrow">Firmas del documento</span><h3>Cinco firmas</h3><p>Completa los cinco espacios con los nombres y cargos correctos antes de guardar. El permisionario se toma del expediente.</p></div>
    <div class="contract-signer-fields"><div><label for="institution-signer">Representante del COBAEM</label><input id="institution-signer" name="institution_signer" maxlength="180" required value="{{ old('institution_signer', $editor?->institution_signer) }}"></div>
        <div><label for="institution-role">Cargo</label><input id="institution-role" name="institution_role" maxlength="180" required value="{{ old('institution_role', $editor?->institution_role) }}"></div>
        <div><label for="witness-signer">Testigo</label><input id="witness-signer" name="witness_signer" maxlength="180" required value="{{ old('witness_signer', $editor?->witness_signer) }}"></div>
        <div><label for="witness-role">Cargo del testigo</label><input id="witness-role" name="witness_role" maxlength="180" required value="{{ old('witness_role', $editor?->witness_role) }}"></div>
        @for($position = 0; $position < 2; $position++)
            <div><label for="signer-title-{{ $position }}">Encabezado de firma {{ $position + 4 }}</label><input id="signer-title-{{ $position }}" name="additional_signers[{{ $position }}][title]" maxlength="100" required value="{{ old('additional_signers.'.$position.'.title', $additionalSigners[$position]['title'] ?? '') }}" placeholder="Ej. TESTIGO"></div>
            <div><label for="signer-name-{{ $position }}">Nombre de firmante {{ $position + 4 }}</label><input id="signer-name-{{ $position }}" name="additional_signers[{{ $position }}][name]" maxlength="180" required value="{{ old('additional_signers.'.$position.'.name', $additionalSigners[$position]['name'] ?? '') }}"></div>
            <div><label for="signer-role-{{ $position }}">Cargo de firmante {{ $position + 4 }}</label><input id="signer-role-{{ $position }}" name="additional_signers[{{ $position }}][role]" maxlength="180" required value="{{ old('additional_signers.'.$position.'.role', $additionalSigners[$position]['role'] ?? '') }}"></div>
        @endfor</div>
    <div class="contract-review-confirm"><label><input type="checkbox" name="confirmacion" value="1" required> Revisé el contenido jurídico, los nombres de firmantes, las fechas fijas y los datos bancarios; eliminé los textos pendientes con asteriscos.</label></div>
    <div class="contract-editor-footer"><span>Campos obligatorios: {permisionario}, {plantel}, {monto}, {fecha_ini}, {fecha_fin}.</span><button class="button" type="submit">Guardar versión revisada</button></div>
</form><aside class="contract-editor-aside"><section class="panel"><span class="eyebrow">Ayuda de edición</span><h2>Campos disponibles</h2><p>Selecciona un campo para insertarlo donde esté el cursor.</p><div class="contract-variables">@foreach($variables as $key => $label)<button type="button" data-token="{{ '{'.$key.'}' }}" title="Insertar {{ $label }}">{{ $label }} <code>{{ '{'.$key.'}' }}</code></button>@endforeach</div></section>
    <section class="panel"><span class="eyebrow">Historial</span><h2>Versiones guardadas</h2>@if($versions->isEmpty())<p>Aún se usa la plantilla original. Al guardar se crea la primera versión local.</p>@else<ol class="contract-versions">@foreach($versions as $version)<li><a href="{{ route('contratos.template', ['service'=>$service,'version'=>$version->id]) }}">Versión #{{ $version->id }} ↗</a><small>{{ $version->editor ?: 'Usuario' }} · {{ \Carbon\Carbon::parse($version->created_at)->format('d/m/Y H:i') }}</small></li>@endforeach</ol>@endif</section></aside></div>
@push('scripts')<script src="{{ asset('vendor/tinymce/tinymce.min.js') }}?v=8.9.2" defer></script><script src="{{ asset('js/contract-tinymce.js') }}?v=1" defer></script>@endpush
@endsection
