@extends('layouts.app')

@section('title', $campus ? 'Editar plantel' : 'Agregar plantel')

@section('content')
<a class="back-link" href="{{ route('planteles.index') }}">← Gestionar planteles</a>
<div class="page-heading"><div><span class="eyebrow">{{ $campus ? 'Plantel '.$campus->id : 'Nuevo registro' }}</span><h1>{{ $campus ? $campus->nombre : 'Agregar plantel' }}</h1><p>Registra sus datos generales y las condiciones disponibles para cada tipo de servicio.</p></div>@if ($campus)<span class="pill {{ $campus->activo ? 'pill-ready' : 'pill-pending' }}">{{ $campus->activo ? 'Activo' : 'Inactivo' }}</span>@endif</div>
@if ($errors->any()) <div class="form-errors" role="alert"><strong>Revisa los datos:</strong><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
<form method="post" action="{{ $campus ? route('planteles.update', $campus->id) : route('planteles.store') }}">@csrf @if ($campus) @method('PUT') @endif
    <section class="panel"><div class="section-bar"><div><span class="eyebrow">Información general</span><h2>Datos del plantel</h2></div></div><div class="campus-fields"><div><label for="campus-name">Plantel o CEMSaD</label><input id="campus-name" name="nombre" maxlength="100" value="{{ old('nombre', $campus?->nombre) }}" required></div><div><label for="campus-email">Correo institucional</label><input id="campus-email" name="correo" type="email" maxlength="100" value="{{ old('correo', $campus?->correo) }}"></div><div class="full-field"><label for="campus-address">Dirección</label><textarea id="campus-address" name="direccion" maxlength="500" rows="3">{{ old('direccion', $campus?->direccion) }}</textarea></div></div></section>
    <div class="section-bar"><div><span class="eyebrow">Configuración dinámica</span><h2>Condiciones por servicio</h2><p class="muted">Activa únicamente los servicios disponibles en este plantel. Los importes son opcionales.</p></div></div>
    <div class="service-condition-grid">@foreach ($services as $service) @php($condition = $conditions->get($service->id))<section class="panel service-condition"><label class="condition-toggle"><input type="checkbox" name="servicios[{{ $service->id }}][habilitado]" value="1" @checked(old('servicios.'.$service->id.'.habilitado', (bool) $condition))><span><strong>{{ $service->nombre }}</strong><small>{{ $service->descripcion }}</small></span></label><div class="condition-fields"><div><label for="space-{{ $service->id }}">Espacio</label><input id="space-{{ $service->id }}" name="servicios[{{ $service->id }}][espacio]" maxlength="50" value="{{ old('servicios.'.$service->id.'.espacio', $condition?->espacio) }}" placeholder="Ej. 149.32 m²"></div><div><label for="enrolment-{{ $service->id }}">Matrícula</label><input id="enrolment-{{ $service->id }}" name="servicios[{{ $service->id }}][matricula]" type="number" min="0" max="999999" value="{{ old('servicios.'.$service->id.'.matricula', $condition?->matricula) }}"></div><div><label for="amount-{{ $service->id }}">Monto</label><input id="amount-{{ $service->id }}" name="servicios[{{ $service->id }}][monto]" type="number" min="0" step="0.01" value="{{ old('servicios.'.$service->id.'.monto', $condition?->monto) }}"></div><div><label for="deposit-{{ $service->id }}">Garantía</label><input id="deposit-{{ $service->id }}" name="servicios[{{ $service->id }}][garantia]" type="number" min="0" step="0.01" value="{{ old('servicios.'.$service->id.'.garantia', $condition?->garantia) }}"></div></div></section>@endforeach</div>
    <div class="sticky-actions"><a class="outline-button button-link" href="{{ route('planteles.index') }}">Cancelar</a><button class="button" type="submit">{{ $campus ? 'Guardar cambios' : 'Agregar plantel' }}</button></div>
</form>
@endsection
