@extends('layouts.app')

@section('title', $document ? 'Editar convocatoria' : 'Nueva convocatoria')

@push('head')<link rel="stylesheet" href="{{ asset('css/emision-convocatorias.css') }}?v=3">@endpush

@section('content')
<div class="emision-shell">
    <a class="emision-back" href="{{ route('emision.index') }}">← Historial de convocatorias</a>
    <section class="emision-hero emision-hero-compact"><div><span class="emision-kicker">{{ $document ? 'Editar documento #'.$document->id : 'Nuevo documento' }}</span><h1>{{ $document ? 'Editar convocatoria' : 'Preparar convocatoria' }}</h1><p>El documento reúne las bases y una fotografía de las condiciones de cada plantel seleccionado.</p></div>@if ($document)<a class="emision-primary" href="{{ route('emision.pdf', $document->id) }}" target="_blank" rel="noopener">Abrir PDF actual ↗</a>@endif</section>
    @if ($errors->any())<div class="emision-errors" role="alert"><strong>Revisa estos datos antes de continuar:</strong><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if (! $call)
        <section class="emision-panel emision-empty"><h2>No hay convocatorias activas con servicio</h2><p>Configura un número de convocatoria y sus planteles antes de preparar el documento.</p><a class="emision-secondary" href="{{ route('convocatorias.index') }}">Ir a número de convocatoria</a></section>
    @else
        <div class="emision-workspace">
            <div class="emision-form-column">
                <section class="emision-panel"><div class="emision-step"><span>01</span><div><span class="emision-kicker">Identidad</span><h2>Datos de la convocatoria</h2></div></div>
                    @if (! $document)<form id="call-switcher" method="get" action="{{ route('emision.create') }}"><label for="convocatoria-selector">Número de convocatoria</label><select id="convocatoria-selector" name="convocatoria" onchange="this.form.submit()">@foreach ($calls as $option)<option value="{{ $option->id }}" @selected($call->id == $option->id)>{{ $option->numero }} · {{ $option->servicio_nombre }}</option>@endforeach</select><p class="emision-hint">Solo aparecen convocatorias activas. Al cambiar el número se cargan sus planteles.</p></form>@else<div class="emision-readonly"><span>Número de convocatoria</span><strong>{{ $call->numero }}</strong><small>{{ $call->servicio_nombre }}</small></div>@endif
                </section>
                <form id="emision-form" method="post" action="{{ $document ? route('emision.update', $document->id) : route('emision.store') }}">@csrf @if ($document) @method('PUT') @endif<input type="hidden" name="convocatoria_id" value="{{ $call->id }}">
                    <section class="emision-panel"><div class="emision-step"><span>02</span><div><span class="emision-kicker">Presentación</span><h2>Título y bases</h2></div></div><div class="emision-field"><label for="emision-title">Título del documento <span>*</span></label><input id="emision-title" name="titulo" maxlength="200" required value="{{ old('titulo', $document?->titulo ?? 'Convocatoria '.$call->numero.' · '.$call->servicio_nombre) }}"><small>Este título aparecerá en el encabezado del PDF.</small></div><div class="emision-field"><label for="emision-details">Requisitos y bases <span>*</span></label><p class="emision-hint">Incluye fechas, forma de entrega, requisitos y condiciones. Revisa el contenido antes de compartir el PDF.</p><div class="emision-editor-toolbar" role="toolbar" aria-label="Formato de requisitos"><button type="button" data-command="bold" title="Negritas"><strong>B</strong></button><button type="button" data-command="italic" title="Cursivas"><em>I</em></button><button type="button" data-command="insertUnorderedList" title="Lista con viñetas">• Lista</button><button type="button" data-command="insertOrderedList" title="Lista numerada">1. Lista</button><button type="button" data-command="formatBlock" data-value="h2" title="Encabezado">H2</button></div><div id="emision-editor" class="emision-editor" contenteditable="true" role="textbox" aria-multiline="true" aria-label="Requisitos y bases" data-placeholder="Escribe aquí los requisitos y las bases de participación..."></div><textarea id="emision-details" name="detalles_html" class="emision-editor-source">{{ old('detalles_html', $document?->detalles_html ?? '') }}</textarea><small>El formato se conserva en el PDF. Por seguridad se eliminan estilos, imágenes y scripts pegados desde otras páginas.</small></div></section>
                    <section class="emision-panel"><div class="emision-step"><span>03</span><div><span class="emision-kicker">Anexo I</span><h2>Planteles participantes</h2></div></div><div class="emision-campus-toolbar"><p>Selecciona los planteles que integran este documento y confirma sus datos.</p><label><input id="emision-all" type="checkbox"> Seleccionar todos</label></div>
                        @if ($campuses->isEmpty())<div class="emision-no-campus">Este número todavía no tiene planteles vinculados. <a href="{{ route('enlaces.edit', $call->id) }}">Asignar planteles</a></div>@endif
                        <div class="emision-bulk-tools"><div><label for="emision-campus-search">Buscar plantel</label><input id="emision-campus-search" type="search" placeholder="Nombre del plantel"></div><div><label for="emision-bulk-date">Fecha de inicio para seleccionados</label><input id="emision-bulk-date" type="date"></div><button id="emision-apply-date" class="emision-secondary" type="button">Aplicar fecha</button></div>
                        <div class="emision-campus-list">@foreach ($campuses as $campus) @php($snapshot = $snapshots->get($campus->id)) @php($base = 'planteles.'.$campus->id) @php($checked = old($base.'.seleccionado', $document ? (bool) $snapshot : true))<article class="emision-campus" data-campus><label class="emision-campus-title"><input class="emision-campus-check" type="checkbox" name="planteles[{{ $campus->id }}][seleccionado]" value="1" @checked($checked)><span><strong>{{ $campus->nombre }}</strong><small>{{ $campus->direccion ?: 'Sin dirección registrada' }}</small></span><span class="emision-campus-state">{{ $checked ? 'Incluido' : 'No incluido' }}</span></label><div class="emision-campus-fields"><div class="wide"><label for="dir-{{ $campus->id }}">Dirección</label><input id="dir-{{ $campus->id }}" name="planteles[{{ $campus->id }}][direccion]" value="{{ old($base.'.direccion', $snapshot?->direccion ?? $campus->direccion) }}" maxlength="500"></div><div><label for="espacio-{{ $campus->id }}">Espacio *</label><input id="espacio-{{ $campus->id }}" name="planteles[{{ $campus->id }}][espacio]" value="{{ old($base.'.espacio', $snapshot?->espacio ?? $campus->espacio) }}" maxlength="100" placeholder="Ej. Local 3"></div><div><label for="matricula-{{ $campus->id }}">Matrícula</label><input id="matricula-{{ $campus->id }}" name="planteles[{{ $campus->id }}][matricula]" type="number" min="0" max="999999" value="{{ old($base.'.matricula', $snapshot?->matricula ?? $campus->matricula) }}"></div><div><label for="monto-{{ $campus->id }}">Monto mensual *</label><input id="monto-{{ $campus->id }}" name="planteles[{{ $campus->id }}][monto]" type="number" min="0" step="0.01" value="{{ old($base.'.monto', $snapshot?->monto ?? $campus->monto) }}" placeholder="0.00"></div><div><label for="garantia-{{ $campus->id }}">Garantía</label><input id="garantia-{{ $campus->id }}" name="planteles[{{ $campus->id }}][garantia]" type="number" min="0" step="0.01" value="{{ old($base.'.garantia', $snapshot?->garantia ?? $campus->garantia) }}" placeholder="0.00"></div><div><label for="fecha-{{ $campus->id }}">Fecha de inicio *</label><input id="fecha-{{ $campus->id }}" name="planteles[{{ $campus->id }}][fecha_inicio]" type="date" value="{{ old($base.'.fecha_inicio', $snapshot?->fecha_inicio) }}"></div></div></article>@endforeach</div>
                    </section>
                    <div class="emision-actions"><span><strong id="emision-count">0</strong> planteles seleccionados</span><div><button class="emision-secondary" type="submit" formaction="{{ route('emision.preview-draft') }}" formtarget="_blank">Vista previa PDF ↗</button><button class="emision-primary" type="submit">{{ $document ? 'Guardar cambios' : 'Guardar convocatoria' }}</button></div></div>
                </form>
            </div>
            <aside class="emision-aside"><div class="emision-aside-card"><span class="emision-kicker">Antes de terminar</span><h3>Revisión del documento</h3><ol><li>Confirma el número y el tipo de servicio.</li><li>Verifica fechas, requisitos y montos.</li><li>Abre la vista previa del PDF.</li><li>Guarda el documento para mantenerlo en el historial.</li></ol><p>Guardar no envía correos a los permisionarios.</p></div>@if ($document)<a class="emision-aside-link" href="{{ route('emision.pdf', ['document' => $document->id, 'descargar' => 1]) }}">↓ Descargar PDF guardado</a>@endif</aside>
        </div>
    @endif
</div>
@endsection

@push('scripts')<script src="{{ asset('js/emision-convocatorias.js') }}?v=3" defer></script>@endpush
